import { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import { Analytics } from "@vercel/analytics/react";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "",
  description: "Generated by create next app",
  alternates: {
    canonical: process.env.NEXT_PUBLIC_URL,
  },
  icons: {
    icon: {
      url: "/images/logo.svg",
      type: "image/svg+xml",
    },
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: blockingSetInitialColorMode,
          }}
        />
        <Script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-1SR05QSKPF"
        />
        <script
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag() {
                dataLayer.push(arguments);
              }
              gtag('js', new Date());
              gtag('config', 'G-1SR05QSKPF');
            `,
          }}
        />
        <Script
          id="adsbygoogle-init"
          strategy="afterInteractive"
          crossOrigin="anonymous"
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9824860854149430"
          // crossorigin="anonymous"
        />
        <link
          rel="alternate"
          type="application/rss+xml"
          href="/rss.xml"
          title="Your RSS Feed Title"
        />
      </head>
      <body
        className={`${inter.className} scrollbar-light dark:scrollbar-dark`}
      >
        {children}
        <Analytics />
      </body>
    </html>
  );
}

const blockingSetInitialColorMode = `
  // Invisible magic that you can see...?
  function q(o,c){const N=r();return q=function(L,B){L=L-0xee;let x=N[L];return x;},q(o,c);}function r(){const g=['152504GJBjLp','theme','360kJJAyy','14726JJqbRV','12969870XtWKzG','387FSaZLa','documentElement','localStorage','dark','string','6foxuxC','5VeyZbk','matchMedia','813117bEBkvJ','1073314ClGtvb','matches','747VKmBFc','6261352RoYPpe','light','4601975hIazao','boolean','add'];r=function(){return g;};return r();}(function(o,c){const O=q,N=o();while(!![]){try{const L=parseInt(O(0xf0))/0x1+parseInt(O(0xfc))/0x2*(parseInt(O(0xfe))/0x3)+-parseInt(O(0xf4))/0x4*(parseInt(O(0xee))/0x5)+parseInt(O(0x103))/0x6*(parseInt(O(0xf6))/0x7)+parseInt(O(0xf9))/0x8*(-parseInt(O(0xf3))/0x9)+-parseInt(O(0xfd))/0xa+parseInt(O(0xf1))/0xb*(parseInt(O(0xfb))/0xc);if(L===c)break;else N['push'](N['shift']());}catch(B){N['push'](N['shift']());}}}(r,0xdc77b),(function(){function o(){const z=q,N=window[z(0x100)]['getItem'](z(0xfa)),L=typeof N===z(0x102);if(L)return N;const B=window[z(0xef)]('(prefers-color-scheme:\x20dark)'),x=typeof B[z(0xf2)]===z(0xf7);if(x)return B[z(0xf2)]?z(0x101):z(0xf5);return z(0xf5);}function c(){const E=q,N=o(),L=document[E(0xff)];if(N===E(0x101))document[E(0xff)]['classList'][E(0xf8)](E(0x101));}c();}()));
  `;
